version: '3'

services:
  fws-data-poller:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        PORT: "${FWS_DATA_POLLER_PORT}"
    ports:
      - "${FWS_DATA_POLLER_PORT}:${FWS_DATA_POLLER_PORT}"
    environment:
      - NODE_ENV=development
    networks:
      - flood_shared_network

networks:
  flood_shared_network:
    external: true