version: '3.8'

services:
  fws-data-poller:
    build:
      context: ..
      dockerfile: docker/dockerfile
    container_name: fws_data_poller
    hostname: fws_data_poller
    ports:
      - "${FWS_DATA_POLLER_PORT}:${FWS_DATA_POLLER_PORT}"
    environment:
      - NODE_ENV=development
    networks:
      - flood_shared_network

networks:
  flood_shared_network:
    external: true