version: '3.8'

services:
  fws-data-poller:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: fws_data_poller
    hostname: fws_data_poller
    ports:
      - "${FWS_DATA_POLLER_PORT}:${FWS_DATA_POLLER_PORT}"
    environment:
      - FWS_INFO_SERVICE_URL=http://fws-info-service:3002/api
    networks:
      - flood_shared_network
    volumes:
      - ../:/usr/src/app

networks:
  flood_shared_network:
    external: true